# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76ff5e4a754e3082c4a95f893111af9c00a0e8c6b27af1ca78890eddae1afdb91120989f8528b8e991089642ab2e3dd16032a50ad408caf98e9792b26fc54d6c

test:
  secret_key_base: a2d1b57651c2d6f2e80b6075151c24c24a284fa3e95af9c9c97fae20017f491f020b4caee1d63c525add420869c75ccb8986aeec63ce2b457c271f3b4795f0e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
